#!/bin/bash
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  KYRO HANDOFF"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Session ended. Before next session, review:"
echo "  • git diff HEAD~1 — what changed"
echo "  • git status — uncommitted work"
echo "  • PLAN.md / KORE_PLAN.md — current objectives"
echo ""
echo "Quality gates:"
echo "  • Wall 1: pre-commit hook (ruff, DRY, TODO scan)"
echo "  • Wall 2: CI gate (konjo-gate.yml)"
echo "  • Wall 3: python3 .konjo/scripts/konjo_review.py (local)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
